AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5


Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
  SupportedStyles:
    - case
    - end

Layout/LineLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb


Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
