name: lint
on:
  push:
    branches-ignore: [debian]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-20.04

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: True

      - run: bundle exec rubocop --fail-level E --extra-details --display-time --color
